feat(composed-schema-restrictions): add new spectral-style rule
IBM/openapi-validator pull request #500
Opened 2022-10-03 22:48 UTC by padamstx

## PR summary
This commit introduces the new spectral-style
'composed-schema-restrictions' rule, which will verify that oneOf and anyOf compositions comply with the restrictions imposed by the SDK generator.

## PR Checklist

### General checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Dependencies have been updated as needed
- [ ] .secrets.baseline updated as needed?

#### Checklist for adding a new validation rule:
- [ ] Added new validation rule definition (packages/ruleset/src/rules/*.js, index.js)
- [ ] If necessary, added new validation rule implementation (packages/ruleset/src/functions/*.js, updated index.js)
- [ ] Added new rule to default configuration (packages/ruleset/src/ibm-oas.js)
- [ ] Added tests for new rule (packages/ruleset/test/*.test.js)
- [ ] Added docs for new rule (docs/ibm-cloud-rules.md)

2022-10-05 14:29 UTC, dpopp07 reviewed
Everything looks good for the most part! Leaving a few comments here prior to approval - curious what you think about the suggestions.

2022-10-05 15:20 UTC, padamstx commented on packages/ruleset/src/functions/composed-schema-restrictions.js
> +  // Next, we need to verify that it's oneOf/anyOf list complies.
Yes NORBERT :joy:

2022-10-05 15:21 UTC, padamstx commented on packages/ruleset/src/functions/composed-schema-restrictions.js
> + * This function checks "schema" and it's oneOf/anyOf list "subSchemas" to verify that
@dpopp07 You missed this one :joy:

2022-10-05 15:26 UTC, padamstx commented on packages/ruleset/src/rules/composed-schema-restrictions.js
> +  severity: 'error',
done

2022-10-05 15:34 UTC, padamstx commented on packages/ruleset/test/composed-schema-restrictions.test.js
> +    it('Compatible properties that are objects (refs, allOf)', async () => {
The root document contains an example of a valid oneOf construction in the Drink schema, which has two object schemas with properties in its oneOf list (Juice, Soda).
The tests that involve allOf are using allOf within an object schema simply as a slightly more complicated way to define the properties within that object schema.  I wanted to make sure that a main schema and its oneOf/anyOf-related sub-schemas could define properties directly with the "properties" field OR they could use allOf to define properties, mainly as a way to prove that the rule's logic handles that case correctly.

2022-10-05 16:38 UTC, padamstx commented on packages/ruleset/src/functions/composed-schema-restrictions.js
> +        message: 'A schema within a oneOf/anyOf list must be an object schema',
fixed it

2022-10-05 16:42 UTC, padamstx commented
@dpopp07 I think I've addressed all your review comments.  Ready for a re-review.

2022-10-05 18:44 UTC, dpopp07 approved these changes
Looks good to me!

2022-10-06 16:48 UTC, pyrooka commented on packages/ruleset/src/functions/composed-schema-restrictions.js
> +  // Next, we need to verify that it's oneOf/anyOf list complies.
Ok, it's official: Dustin has taken my job... 😂

2022-10-06 16:54 UTC, pyrooka approved these changes
LGTM! +1 for the amount of comments, it's really helpful.

2022-10-11 05:18 UTC, hudlow requested changes

2022-10-11 15:53 UTC, padamstx commented on packages/ruleset/src/functions/composed-schema-restrictions.js
> +  unresolvedSpec = context.document.parserResult.data;
we use this technique in a few other rules in order to retrieve the rule's configuration... this is similar but we're just using the original/unresolved spec

2022-10-11 15:54 UTC, padamstx commented on packages/ruleset/src/functions/composed-schema-restrictions.js
> +let unresolvedSpec;
because we need to save off the unresolved spec obtained from the spectral context passed in to the rule function.

2022-10-11 16:23 UTC, padamstx commented on packages/ruleset/src/functions/composed-schema-restrictions.js
> +  }
No, but our generator will support at most one of "allOf", "oneOf", and "anyOf", with the first one found taking precedence.  Should we throw out that assumption within this rule implementation and check both oneOf and anyOf?

2022-10-11 16:25 UTC, padamstx commented on packages/ruleset/src/functions/composed-schema-restrictions.js
> +  }
yes

2022-10-11 16:29 UTC, padamstx commented on packages/ruleset/src/functions/composed-schema-restrictions.js
> +  schema = mergeAllOfSchemaProperties(schema);
The validator seemed to be ok with this schema, but the SDK generator logged an error while processing the allOf list.

2022-10-11 16:33 UTC, padamstx commented on packages/ruleset/src/functions/composed-schema-restrictions.js
> +  // handling of the oneOf/anyOf list (hybrid hierarchy mode).
The purpose of this validator rule was to warn about any oneOf/anyOf compositions that violate the restrictions imposed by the SDK generator.

2022-10-11 18:10 UTC, hudlow commented on packages/ruleset/src/functions/composed-schema-restrictions.js
> +    return p1String === p2String;
I wrote a test that seems to verify expected behavior for resolution, but it's possible Spectral or its underlying dereferencer are buggy and inconsistent. https://github.com/IBM/openapi-validator/pull/503

@padamstx what did you try? I don't want to waste time on this if it's a dead end, but something isn't adding up for me.

2022-10-13 15:57 UTC, padamstx commented
Closing this PR out. Dan will open a new PR when he's ready.

2022-10-13 15:57 UTC, closed without merging