docs: rework and expand docs for utilities package
IBM/openapi-validator pull request #702
Opened 2024-12-04 21:56 UTC by hudlow

## PR summary
Generate dedicated documentation for constants and functions available in the utilities package.

## PR Checklist

### General checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Dependencies have been updated as needed
- [ ] .secrets.baseline updated as needed?

2024-12-05 17:08 UTC, dpopp07 commented
> Should we also update the copyright prologs in the ruleset and validator packages so they're consistent across the project?

I haven't finished my review but I was going to ask about that, too.

Is there a reason they needed to change?

2024-12-06 22:38 UTC, hudlow commented
@padamstx @dpopp07 this was all a part of running the JSDoc plugin for ESLint which, per an offline discussion with Dustin, I have decided to pull out of this PR. I also reverted those header changes and we can add them back if/when we enable JSDoc linting.

2024-12-06 22:49 UTC, padamstx commented
I took a look at the latest changes and I still approve :smile:

2024-12-09 17:50 UTC, dpopp07 requested changes
This looks awesome!

I left a few very, very minor comments that would be good to address before merging.

2024-12-09 17:50 UTC, dpopp07 commented on scripts/generate-utilities-docs.js
> +const mustache = require("mustache");
This JS style for this script should be consistent with the rest of this project (single quotes, trailing commas, etc.)

Is it included in the linting?

2024-12-09 17:50 UTC, dpopp07 commented on scripts/generate-utilities-docs.js
> +const childProcess = require("node:child_process");
Optional nit: this looks fine but when internal Node modules are used elsewhere in the project, we drop the `node:` (which is optional) and use object deconstruction in the imports:

```suggestion
const { readFileSync, writeFileSync } = require('fs');
const { execSync } = require('child_process');
```

This is slightly more semantic than *purely* stylistic so again, I'm happy to keep it as is! Just wanted to make a note for consistency's sake.

2024-12-09 17:50 UTC, dpopp07 commented on scripts/generate-utilities-docs.js
> +  "docs/utilities.md",
Another nit but connecting the doc with the NPM package may provide more clarity for readers
```suggestion
  'docs/openapi-ruleset-utilities.md',
```

2024-12-09 17:50 UTC, dpopp07 commented on packages/utilities/src/collections/index.js
> + * @license Apache-2.0
This looks leftover from the previous changes that are now split out into #703 

I think it's worth keeping this commit clean

2024-12-12 16:15 UTC, dpopp07 approved these changes
Looks great! 👍

2024-12-12 16:19 UTC, merged

2024-12-16 20:50 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 1.25.2 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ibm-cloud/openapi-ruleset/v/1.25.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-16 20:51 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 1.29.1 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/ibm-openapi-validator/v/1.29.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-12-23 21:09 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 1.6.0 :tada:

The release is available on [npm package (@latest dist-tag)](https://www.npmjs.com/package/@ibm-cloud/openapi-ruleset-utilities/v/1.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: